db:
  host:  skyoz-db-3.c980m026m0z2.eu-north-1.rds.amazonaws.com
  username: postgres
  password: Smartkoz1!
  database: postgres
  port: 5432
telegram_token: "7883151332:AAFKuFCP5VK5cG4FP0UQrjNPAjUc8aFmifI"
model_path: models/yolov8n-pose.onnx
org_id: 10720fb6-3c2c-4503-a2d6-f5e619bd07d9

message_queue: 
  host: localhost
  port: 5671
  username: "login"
  password: "password"
  virtual_host: "/"
  heartbeat: 60
  connection_timeout: 30